### ISSUE TITLE
Creating bare-bone project fails

### ISSUE THREAD

**Issue by sven-dibowski** [pitch-io/uix-starter#10]
Hi,

i fail to create a bare bone project with `npx create-uix-app@latest my-app`.

What do i miss?

```
~/Projects$ npx create-uix-app@latest my-app
Downloading project template from https://github.com/pitch-io/uix-starter...
node:internal/errors:540
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1250:7)
    at Unpack.<anonymous> (/home/sven/.npm/_npx/b060ad3aea9e9b3b/node_modules/create-uix-app/src/index.js:84:24)
    at Unpack.emit (node:events:530:35)
    at [maybeClose] (/home/sven/.npm/_npx/b060ad3aea9e9b3b/node_modules/tar/lib/unpack.js:243:12)
    at [unpend] (/home/sven/.npm/_npx/b060ad3aea9e9b3b/node_modules/tar/lib/unpack.js:555:21)
    at /home/sven/.npm/_npx/b060ad3aea9e9b3b/node_modules/tar/lib/unpack.js:455:25
    at FSReqCallback.oncomplete (node:fs:187:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v22.11.0
```

**Comment by roman01la** [comment]
fixed in 1.5.2, thanks for reporting
